// Hand-made pixel art as ASCII rows. '.' is transparent; other characters are
// looked up in the palette passed to paint(), and 'k' is the outline colour.
// Keeping art as data means no binary assets are needed and a test can check
// every sprite's dimensions.
//
// Resolution: a map tile is 32x32 art pixels. Characters and monsters are
// 32x32 with their feet on the bottom row; ground drops are 16x16.

export const OUTLINE = '#1f1a24';

export const SPRITE = 32;
export const DROP = 16;
export const CHAR_HEAD = 32; // top of a character's head, above the feet
export const HAND_X = 8; // where the held weapon sits, from the feet centre
export const HAND_Y = -7;
export const HEAD_BOB = 2; // the walk frame's head is this much lower

// 32x32 character, front view. h/H/D hair (base, shine, strands), s/S skin,
// w eye shine, r blush, m mouth, c/C/L shirt (base, shadow, light), p/P pants,
// b/B shoes. The walk frame drops the head 2px and spreads the legs.
export const CHAR_FRAMES = [
  [
    '...........kkkkkkkkkk...........',
    '.........kkhhhhhhhhhhkk.........',
    '........khhhhhhhhhhhhhhk........',
    '.......khhHHhhhhhhhhHHhhk.......',
    '......khhHHhhhhhhhhhhHHhhk......',
    '......khHHhhhhhhhhhhhhHHhk......',
    '.....khhHhhhhhhhhhhhhhhHhhk.....',
    '.....khhhhhhhhhhhhhhhhhhhhk.....',
    '....khhhhhhhhhhhhhhhhhhhhhhk....',
    '....khhhhhhDhhhhhhhhDhhhhhhk....',
    '....khhhDhhhhhDhhDhhhhhDhhhk....',
    '....khhshhhshhhsshhhshhhshhk....',
    '....khsssssssssssssssssssshk....',
    '....khssskkksssssssskkkssshk....',
    '....khssswkksssssssskkwssshk....',
    '....khssskkksssssssskkkssshk....',
    '....khsrrssssssssssssssrrshk....',
    '.....kssssssssmmmmssssssssk.....',
    '......kksssssssssssssssskk......',
    '........kkkkkkkkkkkkkkkk........',
    '.........kkccCSSSSCcckk.........',
    '.......kkcccccCccCccccckk.......',
    '......kccLccccccccccccLcck......',
    '......kcckcccccccccccckcck......',
    '......kcckcccccccccccckcck......',
    '......ksskCCCCCCCCCCCCkssk......',
    '.......kkkppppppppppppkkk.......',
    '.........kppppPkkPppppk.........',
    '.........kppppPkkPppppk.........',
    '.........kppppPkkPppppk.........',
    '........kbbbbbBkkBbbbbbk........',
    '........kkkkkkk..kkkkkkk........',
  ],
  [
    '................................',
    '................................',
    '...........kkkkkkkkkk...........',
    '.........kkhhhhhhhhhhkk.........',
    '........khhhhhhhhhhhhhhk........',
    '.......khhHHhhhhhhhhHHhhk.......',
    '......khhHHhhhhhhhhhhHHhhk......',
    '......khHHhhhhhhhhhhhhHHhk......',
    '.....khhHhhhhhhhhhhhhhhHhhk.....',
    '....khhhhhhhhhhhhhhhhhhhhhhk....',
    '....khhhDhhhhhDhhDhhhhhDhhhk....',
    '....khhshhhshhhsshhhshhhshhk....',
    '....khsssssssssssssssssssshk....',
    '....khssskkksssssssskkkssshk....',
    '....khssswkksssssssskkwssshk....',
    '....khssskkksssssssskkkssshk....',
    '....khsrrssssssssssssssrrshk....',
    '.....kssssssssmmmmssssssssk.....',
    '......kksssssssssssssssskk......',
    '........kkkkkkkkkkkkkkkk........',
    '.........kkccCSSSSCcckk.........',
    '.......kkcccccCccCccccckk.......',
    '......kccLccccccccccccLcck......',
    '......kcckcccccccccccckcck......',
    '......kcckcccccccccccckcck......',
    '......ksskCCCCCCCCCCCCkssk......',
    '.......kkkppppppppppppkkk.......',
    '........kppppPk..kPppppk........',
    '.......kppppPk....kPppppk.......',
    '.......kppppPk....kPppppk.......',
    '......kbbbbbBk....kBbbbbbk......',
    '......kkkkkkk......kkkkkkk......',
  ],
];

// Fashion overlays, drawn on top of the matching character frame. Hats set
// followsHead so they bob with the walk frame's head.
export const BODY_OVERLAYS = {
  // เสื้อกั๊กวินมอเตอร์ไซค์: orange vest with a reflective stripe, open front.
  vest_win: {
    palette: { o: '#ff7a1a', O: '#c85a0a', y: '#f4f1c0' },
    rows: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '..........ooo......ooo..........',
      '.........oooO......Oooo.........',
      '.........ooooO....Ooooo.........',
      '.........yyyyy....yyyyy.........',
      '.........ooooO....Ooooo.........',
      '.........OOOOO....OOOOO.........',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
    ],
  },
  // หมวกสานเสียบขนนก: straw hat with a pigeon feather.
  hat_straw: {
    followsHead: true,
    palette: { b: '#d9b56e', B: '#8a5a2b', f: '#c9ced6', F: '#8d949e' },
    rows: [
      '...........kkkkkkkkkk...kk......',
      '.........kkbbbbbbbbbbkkkffk.....',
      '........kbbbbbbbbbbbbbbkfFk.....',
      '.......kbbbbbbbbbbbbbbkfFk......',
      '......kBBBBBBBBBBBBBBBkfkk......',
      '......kbbbbbbbbbbbbbbbbbbk......',
      '...kkkkbbbbbbbbbbbbbbbbbbkkkk...',
      '..kbbbbbbbbbbbbbbbbbbbbbbbbbbk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
    ],
  },
  // หมวกสานผักตบ: woven hyacinth hat with a purple flower.
  hat_hyacinth: {
    followsHead: true,
    palette: { g: '#7a9a4a', G: '#556b30', v: '#9b6bd6', V: '#d9c2ff' },
    rows: [
      '...........kkkkkkkkkk.kk........',
      '.........kkgGgGggGgGgkvVk.......',
      '........kgGgGgGggGgGkvVvVk......',
      '.......kGgGgGgGggGgGgkvvk.......',
      '......kgGgGgGgGggGgGgGkkgk......',
      '......kGgGgGgGgGGgGgGgGgGk......',
      '.....kgGgGgGgGgGGgGgGgGgGgk.....',
      '....kkkkkkkkkkkkkkkkkkkkkkkk....',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
    ],
  },
  // งอบหุ่นไล่กา: wide conical straw ngob.
  hat_scarecrow: {
    followsHead: true,
    palette: { y: '#e3c16f', Y: '#b8923f' },
    rows: [
      '..........kkkkkkkkkkkk..........',
      '........kkyyyyYyyYyyyykk........',
      '......kkyyyyyYyyyyYyyyyykk......',
      '.....kyyyyyyYyyyyyyYyyyyyyk.....',
      '....kyyyyyyYyyyyyyyyYyyyyyyk....',
      '...kyyyyyyYyyyyyyyyyyYyyyyyyk...',
      '.kkYYYYYYYYYYYYYYYYYYYYYYYYYYkk.',
      'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
    ],
  },
  // แจ็กเก็ตสายซิ่งงานวัด: black racer jacket with festival LED trim.
  jacket_racer: {
    palette: { j: '#2a2331', J: '#4a3f55', n: '#6dff8a', p: '#f07ab0' },
    rows: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '.........kjjjjn..njjjjk.........',
      '.......kkjjjjjn..njjjjjkk.......',
      '......kjjJjjjjn..njjjjJjjk......',
      '......kjjkjjjjn..njjjjkjjk......',
      '......kjjkjjjjn..njjjjkjjk......',
      '.........knpnpnppnpnpnk.........',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
    ],
  },
  // เสื้อกันฝนกู้ภัย: yellow flood-rescue raincoat with a reflective band.
  raincoat: {
    palette: { y: '#ffd23f', Y: '#c99a1a', r: '#f4f1c0' },
    rows: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '.........kyyyyY..Yyyyyk.........',
      '.......kkyyyyyY..Yyyyyykk.......',
      '......kyyyyyyyyyyyyyyyyyyk......',
      '......kyykyyyyyyyyyyyykyyk......',
      '......krrkrrrrrrrrrrrrkrrk......',
      '.........kyyyyyyyyyyyyk.........',
      '.........kYYYYYYYYYYYYk.........',
      '.........kYYYYYYYYYYYYk.........',
      '.........kkkkkkkkkkkkkk.........',
      '................................',
      '................................',
      '................................',
    ],
  },
  // หัวสิงโตเชิด: lion-dance head with big eyes and a fur trim (สอยดาว prize).
  hat_lion: {
    followsHead: true,
    palette: { r: '#d94f4f', g: '#ffd23f', y: '#e0a040', w: '#fff3d6' },
    rows: [
      '........kkkkkkkkkkkkkkkk........',
      '......kkrrrrrrggggrrrrrrkk......',
      '.....krrrrrrggggggggrrrrrrk.....',
      '....krrkkkkrrggggggrrkkkkrrk....',
      '...wkrkwwwkkrrggggrrkkwwwkrkw...',
      '...wkrkwwkkkrrggggrrkkkwwkrkw...',
      '..wwkrrkkkkrrrrggrrrrkkkkrrkww..',
      '..wwkrrrrrrrrrrrrrrrrrrrrrrkww..',
      '..wwkyyyyyyyyyyyyyyyyyyyyyykww..',
      '...wkkkkkkkkkkkkkkkkkkkkkkkkw...',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
    ],
  },
  // เสื้อลายดอกงานวัด: teal shirt with pink flowers (สอยดาว prize).
  shirt_flower: {
    palette: { b: '#2fb3b3', f: '#f07ab0', y: '#ffe066', w: '#ffffff' },
    rows: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '...........bbw....wbb...........',
      '.........bfbbbw..wbbbfb.........',
      '.......bbfbbfybbbbyfbbfbb.......',
      '.......fy.bbbfybbyfbbb.yf.......',
      '.......bb.bfbbbbbbbbfb.bb.......',
      '..........bbbbbbbbbbbb..........',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
    ],
  },
};

// Held weapons, drawn at the character's right hand (origin 0.5, 0.3).
export const WEAPON_ART = {
  broom: {
    palette: { w: '#8a5a2b', y: '#e3c16f', Y: '#b8923f', r: '#d94f4f' },
    rows: [
      '...kkkk...',
      '...kwwk...',
      '...kwwk...',
      '...kwwk...',
      '...kwwk...',
      '...kwwk...',
      '...kwwk...',
      '...kwwk...',
      '...kwwk...',
      '...kwwk...',
      '...kwwk...',
      '..kkwwkk..',
      '.krrrrrrk.',
      '.krrrrrrk.',
      'kyyYyYYyk.',
      'kyYyyYYyk.',
      'kyYyyYyYk.',
      'kyYyyYyYk.',
      'kyYyyYyYk.',
      'yyYyyYyyYk',
      'yYyyyYyyYk',
      'kYkkkYkkYk',
    ],
  },
  spatula: {
    palette: { w: '#5a3a1b', W: '#7a5230', s: '#8d949e', g: '#c9ced6', G: '#8d949e', L: '#eef0f2' },
    rows: [
      '...kwwk...',
      '...kWwk...',
      '...kwwk...',
      '...kwwk...',
      '...kwwk...',
      '...kWwk...',
      '...kwwk...',
      '...kwwk...',
      '...kwwk...',
      '...kwwk...',
      '...kssk...',
      '...kssk...',
      '.kkksskkk.',
      'kLLLLLLLLk',
      'kggggggggk',
      'kggGGGGggk',
      'kggggggggk',
      'kggGGGGggk',
      'kggggggggk',
      'kggggggggk',
      'kGGGGGGGGk',
      '.kkkkkkkk.',
    ],
  },
  umbrella: {
    palette: { r: '#e0453a', R: '#b0342b', w: '#fff3d6', s: '#5a3a1b' },
    rows: [
      '.......kkkkkk.......',
      '....kkkrrwwwrkkk....',
      '...kwwrrrwwwrrrwk...',
      '..kwwwrrrwwwrrrwwk..',
      '.krwwwrrrwwwrrrwwwk.',
      'krrwwwrrrwwwrrrwwwrk',
      'krrwwwrrrwwwrrrwwwrk',
      'krrwwwrrrwwwrrrwwwrk',
      'kRRwwwRRRwwwRRRwwwRk',
      '.kkkkkkkkskkkkkkkkkk',
      '........kssk........',
      '........kssk........',
      '........kssk........',
      '........kssk........',
      '........kssk........',
      '........kssk........',
      '........kssk........',
      '........kssk........',
      '........kssk........',
      '........kssk........',
      '........kskk........',
      '.........kk.........',
    ],
  },
};

// หนูท่อลมปราณ: sewer rat with a glowing red eye, facing right.
export const RAT_PALETTE = { g: '#7d838c', G: '#aab0b9', d: '#555a63', p: '#f3a0b0', P: '#c8707f', e: '#ff4455', w: '#ffffff' };
export const RAT_FRAMES = [
  [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '.....................k..........',
    '...................kkpkk........',
    '..................kpppppk.......',
    '....k.............kppPppGkk.....',
    '..kkpk............kpPPPpgGGk....',
    '.kpppk...kkkkkkkkkkppPppgggGk...',
    '.kpkk..kkGGGGGGGGGGggpgggwegGk..',
    '.kpk..kGGggggggggggggggggeeggk..',
    '.kpk.kGggggggggggggggggggggggGk.',
    '.kpk.kgggggggggggggggggggggggddP',
    '.kpkkdgggggggggggggggggggggddkk.',
    '.kpppkggggddddddddddddgggddkk...',
    '..kkppdggdGGGGGGGGGGGGdddkk.k...',
    '....kkkddGGGGGGGGGGGGGGkk.......',
    '.......kkdGGGGGGGGGGGdk.........',
    '........kddkkkkkkkkkddk.........',
    '........kpppk......kpppk........',
  ],
  [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '.....................k..........',
    '...................kkpkk........',
    '..................kpppppk.......',
    '....k.............kppPppGkk.....',
    '...kpk............kpPPPpgGGk....',
    '..kpk....kkkkkkkkkkppPppgggGk...',
    '.kpk...kkGGGGGGGGGGggpgggwegGk..',
    '.kpk..kGGggggggggggggggggeeggk..',
    '.kpk.kGggggggggggggggggggggggGk.',
    '.kpk.kgggggggggggggggggggggggddP',
    '.kpkkdgggggggggggggggggggggddkk.',
    '..kpkkggggddddddddddddgggddkk...',
    '...kppdggdGGGGGGGGGGGGdddkk.k...',
    '....kkkddGGGGGGGGGGGGGGdk.......',
    '......kdddGGGGGGGGGGGkddk.......',
    '......kddkkkkkkkkkkkkkddk.......',
    '......kddk...........kddk.......',
    '......kpppk..........kpppk......',
  ],
];

// นกพิราบแย่งข้าว: pigeon with an iridescent neck; frame 1 pecks.
export const PIGEON_PALETTE = { g: '#8a929e', G: '#c3c9d2', d: '#5e6570', i: '#4f9e84', I: '#8e5cc7', e: '#e84a3a', y: '#e0a040', w: '#ffffff' };
export const PIGEON_FRAMES = [
  [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '....................kkkk........',
    '...................kGGGGk.......',
    '..................kGggggGk......',
    '.................kGgggeggGk.....',
    '.................kdggggggdyy....',
    '..................kdggggdky.....',
    '.................kiiddddk.......',
    '..........kkkkkkkkiiiIiIk.......',
    '........kkGGGGGGGiiiiikk........',
    '.......kGGGGGGGGgGiiiik.........',
    '.....kkGGGGddGGGGGGiiiGk........',
    '..kkkdGGGddGdddGGGgGiGgk........',
    '.kddddGGGGdddGddGGggGggdk.......',
    'kddddddgGGGGddGGdddddggk........',
    'kdddddddggdGGGGGGGGGGddk........',
    '.kddddkkddGGGGGGGGGGGGk.........',
    '..kkkk..kkdGGGGGGGGGkk..........',
    '..........kkkkykkkyk............',
    '.............kyk.kyk............',
    '............kyyykyyyk...........',
  ],
  [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '......................kkkk......',
    '.....................kGGGGk.....',
    '....................kGggggGk....',
    '...................kGgggeggGk...',
    '..........kkkkkkkkkkdggggggdyy..',
    '........kkGGGGGGGGiiidggggdky...',
    '.......kGGGGGGGGggiiiiddddk.....',
    '.....kkGGGGddGGGGGGiiiiIkIk.....',
    '..kkkdGGGddGdddGGGgGiiGk.k......',
    '.kddddGGGGdddGddGGggGGgdk.......',
    'kddddddgGGGGddGGdddddggk........',
    'kdddddddggdGGGGGGGGGGddk........',
    '.kddddkkddGGGGGGGGGGGGk.........',
    '..kkkk..kkdGGGGGGGGGkk..........',
    '..........kkkkykkkyk............',
    '.............kyk.kyk............',
    '............kyyykyyyk...........',
  ],
];

// หมาจรจัดประจำซอย: tan soi dog with a red collar.
export const DOG_PALETTE = { b: '#c8924e', B: '#8a5a2b', L: '#e6bb7e', e: '#1f1a24', w: '#ffffff', p: '#e86a7a', n: '#3b2a20', r: '#d94f4f' };
export const DOG_FRAMES = [
  [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '......................k.........',
    '.....................kLk........',
    '.....................kbLk.......',
    '.....................kbBLk......',
    '.....kkk............kLbbbLkk....',
    '....kLLLk...........kbbbbbLLk...',
    '...kLbBBk..........kLbbbbbbbLk..',
    '...kbbkk...........kbbbbbwebbkk.',
    '...kbbk............kbbbbbbbbbLnk',
    '...kbbk..kkkkkkkkkkkbbbbbbbbbbbk',
    '...kBbLkkLLLLLLLLLLkrrbbbbbbbbbk',
    '....kbbLLbbbbbbbbbbLrrbbbbBBBBBk',
    '....kbbbbbbbbbbbbbbbrbrBBBkkpkk.',
    '....kbbbbbbbbbbbbbbbbrrkkk......',
    '...kBbbbbbbbbbbbbbbbbrrBk.......',
    '....kbbbbbBBBBBBBBBBbbbk........',
    '....kBBbBBLLLLLLLLLLBBBk........',
    '.....kkbBLLLLLLLLLLLLBbBk.......',
    '......kbbBLLLLLLLLLkBBbbk.......',
    '......kbbBBkkkkkkkkkBBbbk.......',
    '......kbbBBk.......kBBbbk.......',
    '......kbbBBk.......kBBbbk.......',
    '......kbbBBk.......kBBbbk.......',
    '......kbbBBk.......kBBbbk.......',
    '......kbbbBBk......kBBbbbk......',
  ],
  [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '......................k.........',
    '.....................kLk........',
    '.....................kbLk.......',
    '.....................kbBLk......',
    '...kk...............kLbbbLkk....',
    '..kLLk..............kbbbbbLLk...',
    '.kLbBk.............kLbbbbbbbLk..',
    '.kbbk..............kbbbbbwebbkk.',
    '.kbbk..............kbbbbbbbbbLnk',
    '.kbbLk...kkkkkkkkkkkbbbbbbbbbbbk',
    '.kBbbLkkkLLLLLLLLLLkrrbbbbbbbbbk',
    '..kBbbLLLbbbbbbbbbbLrrbbbbBBBBBk',
    '...kBbbbbbbbbbbbbbbbrbrBBBkkppk.',
    '....kbbbbbbbbbbbbbbbbrrkkk......',
    '...kBbbbbbbbbbbbbbbbbrrBk.......',
    '....kbbbbbBBBBBBBBBBbbbk........',
    '....kBBbBBLLLLLLLLLLBBBkkk......',
    '....kbBBLLLLLLLLLLLLLkkkbBk.....',
    '....kbbkkBLLLLLLLLLBk..kbbk.....',
    '....kbbk.kkBBkkkkkBBk..kbbk.....',
    '....kbbk..kBBk...kBBk..kbbk.....',
    '....kbbk..kBBk...kBBk..kbbk.....',
    '....kbbk..kBBk...kBBk..kbbk.....',
    '....kbbk..kBBk...kBBk..kbbk.....',
    '....kbbbk.kBBBk..kBBBk.kbbbk....',
  ],
];

// ผักตบชวากลายพันธุ์: floating hyacinth clump with a flower spike and angry eyes.
export const HYACINTH_PALETTE = { g: '#3f8a36', G: '#7ccc55', d: '#2a5e25', v: '#9b6bd6', V: '#d9c2ff', w: '#5b93b3', W: '#9cc8e0', e: '#ffe066', s: '#8fbf5a' };
export const HYACINTH_FRAMES = [
  [
    '................................',
    '...............kkk..............',
    '..............kvvvk.............',
    '.............kkvVvk.............',
    '............kvvvvvkk............',
    '............kvVvvvvvk...........',
    '............kvvvkvVvk...........',
    '............kvvvvvvvk...........',
    '..........kkkkvVvvvvkk..........',
    '.........kGGGGvvvvGGGGk.........',
    '........kGggggGvvVggggGk........',
    '.......kkggggggkvggggggkk.......',
    '......kGGgggdggkvgggdggGGk......',
    '.....kGgggggdggksgggdggggGk.....',
    '....kGggggggdggksgggdgggggGk....',
    '...kGgggggggdggksgggdggggggGk...',
    '...kggggggggdggGGgggdgggggggk...',
    '...kdggggggggggggggggggggggdk...',
    '...kddggggggggggggggggggggddk...',
    '....kddggggggggggggggggggddk....',
    '.....kdggggkkggggggggkkggdk.....',
    '......kggggkekgggggkekgggk......',
    '......kgggggkkgggggkkggggk......',
    '......kdggggggggggggggggdk......',
    '......kddggggggggggggggddk......',
    '.......kdddggkkkkkkggdddk.......',
    '........kddddddddddddddk........',
    '.........kkddddddddddkk.........',
    '...........kkkkkkkkkk...........',
    '..WWwwwwwwwwwwwwwwwwwwwwwwwwWW..',
    '.WwwwWWwwwwwwwWWwwwwwwwWWwwwwwW.',
    '..wwww..wwwwwwww..wwwwwwww..ww..',
  ],
  [
    '................................',
    '................kkk.............',
    '...............kvvvk............',
    '..............kkvVvk............',
    '.............kvvvvvkk...........',
    '.............kvVvvvvvk..........',
    '.............kvvvkvVvk..........',
    '.............kvvvvvvvk..........',
    '..............kvVvGGGGk.........',
    '..........kkkkkvvGggggGk........',
    '.........kGGGGkvvgVggggkk.......',
    '........kGggggGkkggggggGGk......',
    '.......kkgggdggksgggdggggGk.....',
    '......kGGgggdggksdggdgggggGk....',
    '.....kGgggggdggksdggdggggggGk...',
    '....kGggggggdggkssggdgggggggk...',
    '...kGgggggggdggGGGggdggggggdk...',
    '...kggggggggggggggggggggggddk...',
    '...kdggggggggggggggggggggddk....',
    '...kddgggggggggggggggggggdk.....',
    '....kddggggkkggggggggkkggk......',
    '.....kdggggkekgggggkekgggk......',
    '......kgggggkkgggggkkggggk......',
    '......kdggggggggggggggggdk......',
    '......kddggggggggggggggddk......',
    '.......kdddggkkkkkkggdddk.......',
    '........kddddddddddddddk........',
    '.........kkddddddddddkk.........',
    '...........kkkkkkkkkk...........',
    'WWwwwwwwwwwwwwwwwwwwwwwwwwWW....',
    'wwwWWwwwwwwwWWwwwwwwwWWwwwwwW..W',
    'wwww..wwwwwwww..wwwwwwww..ww....',
  ],
];

// ตัวเงินตัวทอง: long monitor lizard with yellow bands; frame 1 flicks its tongue.
export const MONITOR_PALETTE = { d: '#3b3a2e', D: '#5d5a44', L: '#7a7658', y: '#e3c16f', e: '#ffcf3f', t: '#e86a7a' };
export const MONITOR_FRAMES = [
  [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '........................kkkk....',
    '.........kkkkkkkkkkkkkkkLLLLk...',
    '.......kkLLLLLLLLLLLLLLLDDeDLkk.',
    '.....kkLLDDDyyDDDDyyDDDDDDDDDddk',
    '..kkkLLDDyyDDDDyyDDDDyyDDDDDdkk.',
    'kkLLLDyyDDDDDDDDDDDDDDDDddddk...',
    'LLDyydddDDDDDDDDDDDDDDDDkkkk....',
    'dddddkkkDDDDddddddddDDDDk.......',
    'kkkkk.kLDdDDkkkkkkkkDDdDLk......',
    '......kDDkDDk......kDDkDDk......',
    '.....kdddkdddk....kdddkdddk.....',
  ],
  [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '........................kkkk....',
    '.........kkkkkkkkkkkkkkkLLLLk...',
    '.......kkLLLLLLLLLLLLLLLDDeDLkk.',
    '...kkkkLLDDDyyDDDDyyDDDDDDDDDddk',
    'kkkLLLLDDyyDDDDyyDDDDyyDDDDDdkkt',
    'LLLDDDyyDDDDDDDDDDDDDDDDddddk.t.',
    'dddyyddddDDDDDDDDDDDDDddkkkk....',
    'kkkkkkkkkDDDDDddddDDDDkk........',
    '........kDDdDDkkkkDDdDLk........',
    '........kDDkDDk..kDDkDDk........',
    '.......kdddkdddkkdddkdddk.......',
  ],
];

// มวลน้ำท่วม: muddy wave with a curling crest. Drawn at double size.
export const FLOOD_PALETTE = { b: '#6b5a3a', B: '#8a7450', D: '#4a3d27', w: '#5b93b3', W: '#9cc8e0', f: '#e8f4ff', e: '#ff4455' };
export const FLOOD_FRAMES = [
  [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '...................kkkfk........',
    '................kkkWWWWWkkf.....',
    '.............kkkWWWWWWWWWWWk....',
    '............kwwWWWWwwwwwwWWWk...',
    '...........kwwwwwwwwwwwwwwwwwkf.',
    '..........kwwwwwwbbbbbDkkwwwwfk.',
    '.........kwwwwbbbbbbbDk..kkkkk.f',
    '........kwwwbbbbbbbbbk......f...',
    '.......kwwwbbbbbbbbbbk..........',
    '......kBwwbbbbbbbbbbbBk.........',
    '......kBbbbbbbbbbbbbbBk.........',
    '.....kBbbkkkbbbbbbkkkbBkk.......',
    '....kBBbbbkekbbbbeekbbBBBk......',
    '....kBbbbbbkkbbbbkkbbbbBBBk.....',
    '...kBbbbbbbbbbbbbbbbbbbbbBBk....',
    '...kBbbbbbbbbbbbbbbbbbbbbbBk....',
    '...kbbbbbbkkkkkkkkbbbbbbbbbBk...',
    '...kbbbbbbkfkfkfkkbbbbbbbbbBBk..',
    '...kbbbbbbbkkkkkkbbbbbbbbbbbBk..',
    '..kBbbbbbbbbbbbbbbbbbbbbbbbbbk..',
    '..kBbbbbbbbbbbbbbbbbbbbbbbbbbk..',
    '..kbbbbbbbbbbbbbbbbbbbbbbbbbbBk.',
    '..kbbbbbbbbbbbbbbbbbbbbbbbbbbBk.',
    '.fWfWWwwwwwwwwwwwwwwwwwwwwWWfWf.',
    'fWWfWWfWWfWWfWWfWWfWWfWWfWWfWWf.',
  ],
  [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '....................kkfk........',
    '.................kkkWWWWkkf.....',
    '...............kkWWWWWWWWWWk....',
    '.............kkWWWWWWWWWWWWWk...',
    '............kwwWWWWwwwwwwWWWWk..',
    '...........kwwwwwwwwwwwwwwwwwkf.',
    '..........kwwwwwwbbbbbDkkwwwwfk.',
    '.........kwwwwbbbbbbbDk..kkkkk.f',
    '........kwwwbbbbbbbbbk......f...',
    '.......kwwwbbbbbbbbbbk..........',
    '......kBwwbbbbbbbbbbbBk.........',
    '......kBbbbbbbbbbbbbbBk.........',
    '.....kBbbkkkbbbbbbkkkbBkk.......',
    '....kBBbbbkekbbbbeekbbBBBk......',
    '....kBbbbbbkkbbbbkkbbbbBBBk.....',
    '...kBbbbbbbbbbbbbbbbbbbbbBBk....',
    '...kBbbbbbbbbbbbbbbbbbbbbbBk....',
    '...kbbbbbbkkkkkkkkbbbbbbbbbBk...',
    '...kbbbbbbkfkfkfkkbbbbbbbbbBBk..',
    '...kbbbbbbbkkkkkkbbbbbbbbbbbBk..',
    '..kBbbbbbbbbbbbbbbbbbbbbbbbbbk..',
    '..kBbbbbbbbbbbbbbbbbbbbbbbbbbk..',
    '..kbbbbbbbbbbbbbbbbbbbbbbbbbbBk.',
    '..kbbbbbbbbbbbbbbbbbbbbbbbbbbBk.',
    'fWfWWwwwwwwwwwwwwwwwwwwwwWWfWfk.',
    'WWfWWfWWfWWfWWfWWfWWfWWfWWfWWf.f',
  ],
];

// หุ่นไล่กาสเต็ปเทพ: scarecrow in an ngob hat and plaid shirt; frame 1 kicks a leg.
export const SCARECROW_PALETTE = { y: '#e3c16f', Y: '#b8923f', c: '#d94f4f', C: '#9c2b24', w: '#8a5a2b', W: '#5e3e22', s: '#d9c9a0', S: '#b8a67a', e: '#1f1a24', b: '#3b82c4' };
export const SCARECROW_FRAMES = [
  [
    '.............kkyykk.............',
    '...........kkyyyyyyk............',
    '..........kyyyyyyyyykk..........',
    '........kkyyyyyyyyyyyykk........',
    '......kkyyyyyyyyyyyyyyyykkk.....',
    '.....kYYYYYYYYYYYYYYYYYYYYYk....',
    '......kkkkksssssssssskkkkkk.....',
    '..........kssssssssssk..........',
    '..........kssessesessk..........',
    '..........kssssssssssk..........',
    '..........kssssssssssk..........',
    '..........kSseeeeessSk..........',
    '.k.......ykkSSssssSSk.y......k..',
    'kyk...kkkkCccCSSSScCckCkkk..kyk.',
    'kyykkkccccCccCbbbbcCccCccckkyyk.',
    'kyywwwccccCccCbbbbcCccCcccwyyyk.',
    'kykwwwcccCCCCCbbbbCCCCCcccwwyyk.',
    '.k.kkkccccCccCbbbbcCccCccckkkyk.',
    '.....kccccCccCbbbbcCccCccck..k..',
    '......kkkcCccCbbbbcCckCkkk......',
    '........kCCCCCbbbbCCCCCk........',
    '........kcCccCbbbbcCccCk........',
    '........kcCccCbbbbcCccCk........',
    '........kcCccCbbbbcCccCk........',
    '........kCCCCCbbbbCCCCCk........',
    '........kcCccCbbbbcCccCk........',
    '.........kykkCbbbbyCkyCk........',
    '..........k.kyywwkyyk.k.........',
    '...........kyyywwkyyyk..........',
    '...........kyykwwkkyyk..........',
    '..........kyyykkk.kyyyk.........',
    '..........kyyyk...kyyyk.........',
  ],
  [
    '.............kkyykk.............',
    '...........kkyyyyyyk............',
    '..........kyyyyyyyyykk..........',
    '........kkyyyyyyyyyyyykk........',
    '......kkyyyyyyyyyyyyyyyykkk.....',
    '.....kYYYYYYYYYYYYYYYYYYYYYk....',
    '......kkkkksssssssssskkkkkk.....',
    '..........kssssssssssk..........',
    '..........kssessesessk..........',
    '..........kssssssssssk..........',
    '..........kssssssssssk..........',
    '.k........kSseWeWessSk..........',
    'kyk...kkkykkSSssssSSkkykkk......',
    'kyykkkccccCccCSSSScCccCccckkkk..',
    'kyywwwccccCccCbbbbcCccCcccwyyyk.',
    'kykwwwccccCccCbbbbcCccCcccwwyyk.',
    '.k.kkkcccCCCCCbbbbCCCCCccckkkyk.',
    '.....kccccCccCbbbbcCccCccck..k..',
    '......kkkkCccCbbbbcCckCkkk......',
    '........kcCccCbbbbcCckCk........',
    '........kCCCCCbbbbCCCCCk........',
    '........kcCccCbbbbcCccCk........',
    '........kcCccCbbbbcCccCk........',
    '........kcCccCbbbbcCccCk........',
    '........kCCCCCbbbbCCCCCk........',
    '........kcCccCbbbbcCccCk........',
    '.........kykkCbbbbyCyyCk........',
    '..........k.kyywwkyyyykkk.......',
    '...........kyyywwkkkyyyyyk......',
    '...........kyyywwk..kyyyyyk.....',
    '...........kyykkk....kkkyyk.....',
    '...........kyyk.........kk......',
  ],
];

// ฝูงแตนแตกรัง: three wasps buzzing together.
export const WASP_PALETTE = { y: '#ffd23f', Y: '#c99a1a', b: '#1f1a24', w: '#e8f4ff', W: '#b9d8ee', r: '#ff4455' };
export const WASP_FRAMES = [
  [
    '................................',
    '................................',
    '.....wwWWWW.......wwwWWWW.......',
    '....wwwWWWW......wwwwWWWW.k.....',
    '....wwwWWWW......kyyykkYYkyk....',
    '....kww.WWk.k...kybybyYYYyyrk...',
    '...kyyykkYYkyk.kyybybyYYYyyyk...',
    '..kybybyYYYyyrkkrybybykYYkyk....',
    '.kyybybyYYYyyyk.kkbybk.kk.k.....',
    '.krybybykYYkyk....kkk...........',
    '..kkbybk.kk.k...................',
    '....kkk.........................',
    '................................',
    '................................',
    '..........wwwWWWW...............',
    '.........wwwwWWWW.k.............',
    '.........kyyykkYYkyk............',
    '........kybybyYYYyyrk...........',
    '.......kyybybyYYYyyyk...........',
    '.......krybybykYYkyk............',
    '........kkbybk.kk.k.............',
    '..........kkk...................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
  ],
  [
    '................................',
    '................................',
    '................................',
    '................................',
    '.......wwWWWW......wwwWWWW......',
    '......wwwWWWW.....wwwwWWWW.k....',
    '......wwwWWWW.....kyyykkYYkyk...',
    '......kww.WWk.k..kybybyYYYyyrk..',
    '.....kyyykkYYkykkyybybyYYYyyyk..',
    '....kybybyYYYyyrkrybybykYYkyk...',
    '...kyybybyYYYyyykkkbybk.kk.k....',
    '...krybybykYYkyk...kkk..........',
    '....kkbybwwwWWWW................',
    '......kkwwwwWWWW.k..............',
    '........kyyykkYYkyk.............',
    '.......kybybyYYYyyrk............',
    '......kyybybyYYYyyyk............',
    '......krybybykYYkyk.............',
    '.......kkbybk.kk.k..............',
    '.........kkk....................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
  ],
];

// ควายเหล็กคลั่ง: riveted iron buffalo with big horns; frame 1 snorts steam.
export const BUFFALO_PALETTE = { i: '#6e7682', I: '#9aa3ad', d: '#4a5059', h: '#e8e0c8', H: '#b8ad90', e: '#ff4455', r: '#c9ced6', s: '#e8f4ff' };
export const BUFFALO_FRAMES = [
  [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '.....................kk.........',
    '....................khhk..kk....',
    '....................khhk.kHHk...',
    '...................khhhk.kHHHk..',
    '...................khhhk.kHHHk..',
    '...................khhk...kHHHk.',
    '.......kkkkkkkkkkkkkhhhk...kHHk.',
    '.....kkIIIIIIIIIdIIkkhhhk.khhhk.',
    '...kkIIidiiiiiiidiiIIhhhkkkhhhk.',
    '..kIIiiidiriiiridiriiIhhhIIhhk..',
    '..kiiiridiiiiiiidiiiiiihhiihhk..',
    '.kIiiiiidiiiiiiidiiiiiiiiiiiiIk.',
    '.kdiiiiidiiiiiiidiiiiiiiiiikeik.',
    '.kdiiiiidiiiiiiidiiiiiiiiiikkik.',
    'kdkdiiiidiiiiiiidiiiiiiiiiiiiik.',
    'kdkddiridiiiiiiidiiiiddddiiiiidk',
    'ddkkdddidiriiiridirddddddddiikdk',
    'kk..kiiddddddddddddddkiiddddddk.',
    '....kiidddddddddddddddiidkkdddk.',
    '....kiiddddkkkkkdkkdddiidk.kkk..',
    '....kiiddddk....k.kdddiidk......',
    '....kiiddddk......kdddiidk......',
    '....kiiddddk......kdddiidk......',
    '....kiiddddk......kdddiidk......',
    '.....kkkkkk........kkkkkk.......',
  ],
  [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '.....................kk.........',
    '....................khhk..kk....',
    '....................khhk.kHHk...',
    '...................khhhk.kHHHk..',
    '...................khhhk.kHHHk..',
    '...................khhk...kHHHk.',
    '.......kkkkkkkkkkkkkhhhk...kHHk.',
    '.....kkIIIIIIIIIdIIkkhhhk.khhhk.',
    '...kkIIidiiiiiiidiiIIhhhkkkhhhk.',
    '..kIIiiidiriiiridiriiIhhhIIhhk..',
    '..kiiiridiiiiiiidiiiiiihhiihhk..',
    '.kIiiiiidiiiiiiidiiiiiiiiiiiiIk.',
    '.kdiiiiidiiiiiiidiiiiiiiiiikeik.',
    '.kdiiiiidiiiiiiidiiiiiiiiiikkik.',
    'kdkdiiiidiiiiiiidiiiiiiiiiiiiik.',
    'kdkddiridiiiiiiidiiiiddddiiiiidk',
    'ddkkdddidiriiiridirddddddddiikdk',
    'kkkiiddddddddddddddddkkkiiddddk.',
    '..kiidkdddddddddddddk..kiiddddk.',
    '..kiidkkkkdddkkkddddk..kiidkks.s',
    '..kiidk..kdddk..kdddk..kiidk..s.',
    '..kiidk..kdddk..kdddk..kiidk....',
    '..kiidk..kdddk..kdddk..kiidk....',
    '..kiidk..kdddk..kdddk..kiidk....',
    '...kkk....kkk....kkk....kkk.....',
  ],
];

// รถพ่วงข้างแต่งซิ่ง: neon sidecar bike with a festival speaker stack. Drawn at triple size.
export const SIDECAR_PALETTE = { r: '#e0453a', R: '#9c2b24', l: '#ff8a7a', s: '#3b3f47', S: '#8d949e', n: '#6dff8a', p: '#f07ab0', w: '#e8e8e8', y: '#ffd23f', c: '#2c2733', g: '#c9ced6' };
export const SIDECAR_FRAMES = [
  [
    '..kkkkkkkkkkk...................',
    '.kccccccccccck..................',
    '.kccccSSScccck..................',
    '.kcccSSsSSccck..................',
    '.kcccSsgsSccck..................',
    '.kcccSsssSccck..................',
    '.kcccSSSSSccck..................',
    '.kcccccSccccck............kkkkk.',
    '.kpppppppppppk...........ksssssk',
    'kccccccccccccck..........ksssssk',
    'kccccccccccccck...........ksskk.',
    'kcccScccccSccck...........ksk...',
    'kcSSsSScSSsSSck...........ksk...',
    'kcSsssScSsssSck..........ksk....',
    'kSssgssSssgssSkkkkkkkk..kksk....',
    'kcSsssScSsssSckssssssskklllk....',
    'kcSSsSScSSsSScksssssssllrrrlk...',
    'kcccScccccScccllllllllrrrrrrlk..',
    'kcccccccccccccrrrrrrrrrrrrrrryy.',
    'kppppppppppppprrrrrrrrrrrrrrryk.',
    'kRrrrrrrrrrrrrrrrrrrrrrrrrrrrRk.',
    '.krrrrrrrrrrrrrrrrrrrrrrrrrrrk..',
    '.krrrrrrrrrrrrrrrrrrrrRRRRRRRk..',
    '.kRrrrsssrrrrrrRRRRRRRkkssskk...',
    '..knnnnnnnnnnnnnnnnnnnnnnnnnnn..',
    '...kssssssskkkk......ksssssssk..',
    '..ksssgggsssk.......ksssgggsssk.',
    '..ksgsgggsgsk.......ksgsgggsgsk.',
    '..ksssgggsssk.......ksssgggsssk.',
    '...ksssssssk.........ksssssssk..',
    '....kssgssk...........kssgssk...',
    '.....ksssk.............ksssk....',
  ],
  [
    '..kkkkkkkkkkk...................',
    '.kccccccccccck..................',
    '.kccccSSScccck..................',
    '.kcccSSsSSccck..................',
    '.kcccSsgsSccck..................',
    '.kcccSsssSccck..................',
    '.kcccSSSSSccck..................',
    '.kcccccSccccck............kkkkk.',
    '.knnnnnnnnnnnk...........ksssssk',
    'kccccccccccccck..........ksssssk',
    'kccccccccccccck...........ksskk.',
    'kcccScccccSccck...........ksk...',
    'kcSSsSScSSsSSck...........ksk...',
    'kcSsssScSsssSck..........ksk....',
    'kSssgssSssgssSkkkkkkkk..kksk....',
    'kcSsssScSsssSckssssssskklllk....',
    'kcSSsSScSSsSScksssssssllrrrlk...',
    'kcccScccccScccllllllllrrrrrrlk..',
    'kcccccccccccccrrrrrrrrrrrrrrryy.',
    'knnnnnnnnnnnnnrrrrrrrrrrrrrrryk.',
    'kRrrrrrrrrrrrrrrrrrrrrrrrrrrrRk.',
    '.krrrrrrrrrrrrrrrrrrrrrrrrrrrk..',
    '.krrrrrrrrrrrrrrrrrrrrRRRRRRRk..',
    '.kRrrrsssrrrrrrRRRRRRRkkssskk...',
    '..kppppppppppppppppppppppppppp..',
    '...ksgsssgskkkk......ksgsssgsk..',
    '..ksssgggsssk.......ksssgggsssk.',
    '..ksssgggsssk.......ksssgggsssk.',
    '..ksssgggsssk.......ksssgggsssk.',
    '...ksgsssgsk.........ksgsssgsk..',
    '....ksssssk...........ksssssk...',
    '.....ksssk.............ksssk....',
  ],
];

// Every monster type's sprite frames, palette, head height (art pixels above
// the feet, for the name tag and HP bar) and optional display scale.
export const MONSTER_ART = {
  rat: { frames: RAT_FRAMES, palette: RAT_PALETTE, headY: 17 },
  pigeon: { frames: PIGEON_FRAMES, palette: PIGEON_PALETTE, headY: 20 },
  dog: { frames: DOG_FRAMES, palette: DOG_PALETTE, headY: 25 },
  hyacinth: { frames: HYACINTH_FRAMES, palette: HYACINTH_PALETTE, headY: 31 },
  monitor: { frames: MONITOR_FRAMES, palette: MONITOR_PALETTE, headY: 11 },
  flood: { frames: FLOOD_FRAMES, palette: FLOOD_PALETTE, headY: 25, scale: 2 },
  scarecrow: { frames: SCARECROW_FRAMES, palette: SCARECROW_PALETTE, headY: 32 },
  wasp: { frames: WASP_FRAMES, palette: WASP_PALETTE, headY: 30 },
  buffalo: { frames: BUFFALO_FRAMES, palette: BUFFALO_PALETTE, headY: 25 },
  sidecar: { frames: SIDECAR_FRAMES, palette: SIDECAR_PALETTE, headY: 32, scale: 3 },
};

// Props held in the other hand (left, when facing right). `oy` is where the
// hand grips, as a fraction of the height from the top.
export const PROP_ART = {
  prop_oliang: {
    oy: 0.08,
    palette: { r: '#e86a7a', g: '#e8f4ff', o: '#6b4226', w: '#ffffff', s: '#f07ab0' },
    rows: [
      '...krrrk..',
      '..krkkkrk.',
      '..krk.srk.',
      '..krkksrk.',
      '..kgggsk..',
      '.kwggggs..',
      '.kgggggsk.',
      '.kgggggsk.',
      'kgooooook.',
      'kgowoooogk',
      'kgoooooogk',
      'kgoooowogk',
      'kgooooook.',
      '.koowoook.',
      '.kooooook.',
      '..kkkkkk..',
    ],
  },
  prop_fan: {
    oy: 0.75,
    palette: { h: '#f4f1c0', c: '#7ee0c8', b: '#d8fff4', w: '#9cc8e0', B: '#c9ced6' },
    rows: [
      '..kkkkkk..',
      '.kcccccck.',
      'kccbbwbcck',
      'kcbbbbbbck',
      'kcbbbbbbck',
      'kcbwbhbwck',
      'kcbbbbbbck',
      'kccbbbbcck',
      '.kcccwcck.',
      '..kkhhkk..',
      '...khhk...',
      '...khhk...',
      '...kBhk...',
      '...khhk...',
      '...khhk...',
      '...khhk...',
    ],
  },
  prop_basket: {
    oy: 0.05,
    palette: { w: '#8a5a2b', y: '#c8924e', Y: '#8a5a2b' },
    rows: [
      '...kwwwwwk....',
      '...kwkkkkwk...',
      '..kwwk...kwk..',
      '..kwk....kwk..',
      '.kkwkkkkkkwkk.',
      'kwwwwwwwwwwwwk',
      'kyYYYYYYYYYYYk',
      '.kyYyyYyyYyyk.',
      '.kYYYYYYYYYYYk',
      '.kyYyyYyyYykk.',
      '.kYYYYYYYYYYYk',
      '..kkkkkkkkkkk.',
    ],
  },
};

// 16x16 pets that follow their owner, side view facing right, 2 walk frames.
export const PET_ART = {
  pet_chick: {
    palette: { b: '#c8743a', B: '#e3a15a', g: '#2f6b4a', G: '#1f4a33', r: '#e0453a', y: '#e0a040' },
    frames: [
      [
        '..k.............',
        '.kGk............',
        '.kGGk....krrk...',
        'kggGGk..kbbrbk..',
        '.kgGGk..kbbkbk..',
        '.kgGGGkkkbbbby..',
        '..kgGkbbbbbbbk..',
        '...kbbbbbbbbrk..',
        '...kbbBBBbbbk...',
        '..kbbBBBBBbbbk..',
        '...kbBBBBBbbk...',
        '...kbbBBBbbbk...',
        '....kkbbbbkk....',
        '......kykyk.....',
        '......kykyk.....',
        '......kyyyyk....',
      ],
      [
        '..k.............',
        '.kGk............',
        '.kGGk...........',
        'kggGGk..........',
        '.kgGGk..........',
        '.kgGGGkkkkkrrk..',
        '..kgGkbbbbbbrbk.',
        '...kbbbbbbbbkbk.',
        '...kbbBBBbbbbby.',
        '..kbbBBBBBbbbbk.',
        '...kbBBBBBbbbrk.',
        '...kbbBBBbbbkk..',
        '....kkbbbbkk....',
        '......kykyk.....',
        '......kykyk.....',
        '......kyyyyk....',
      ],
    ],
  },
  pet_cat: {
    palette: { o: '#f0923a', O: '#c86a1a', w: '#fff3d6', p: '#f3a0b0' },
    frames: [
      [
        '................',
        '..kk............',
        '.kook.....k.....',
        '.kok.....kok.k..',
        'kook.....kookok.',
        'kok......kooook.',
        'kok.....kooooook',
        'kok...kkkooookok',
        'kookkkooooooooop',
        '.kooooOoOoOoook.',
        '..kooooooooook..',
        '..kooooooooook..',
        '..koowwwwwwook..',
        '...kokwwwwokOk..',
        '...kokOkkkokOk..',
        '...kokOk.kokOk..',
      ],
      [
        '................',
        '....kk..........',
        '...kook...k.....',
        '..kook...kok.k..',
        '.kook....kookok.',
        '.kok.....kooook.',
        '.kok....kooooook',
        '.kok..kkkooookok',
        '.kookkooooooooop',
        '..koooOoOoOoook.',
        '..kooooooooook..',
        '..kooooooooook..',
        '..koowwwwwwook..',
        '...kkowwwwkOk...',
        '....kokOkokOk...',
        '....kokOkokOk...',
      ],
    ],
  },
  pet_dog: {
    palette: { b: '#b8683a', B: '#7a4020' },
    frames: [
      [
        '................',
        '...........k....',
        '..........kbk...',
        '.k........kbbk..',
        'kbk.......kbbbk.',
        'kbk....k.kbbbbbk',
        'kbbkkkkbkkbbbkbk',
        '.kbBBBBBBBBbbbbk',
        '.kbbbbbbbbbbbbbk',
        '.kbbbbbbbbbbbkk.',
        '.kbbbbbbbbbbbk..',
        '..kbbbbbbbbbbk..',
        '..kBkbkbkkBkbk..',
        '..kBkbkk.kBkbk..',
        '..kBkbk..kBkbk..',
        '..kBkbk..kBkbk..',
      ],
      [
        '................',
        '...........k....',
        '..........kbk...',
        '.k........kbbk..',
        'kbk.......kbbbk.',
        'kbk....k.kbbbbbk',
        'kbbkkkkbkkbbbkbk',
        '.kbBBBBBBBBbbbbk',
        '.kbbbbbbbbbbbbbk',
        '.kbbbbbbbbbbbkk.',
        '.kbbbbbbbbbbbk..',
        '..kbbbbbbbbbk...',
        '...kBkbbkBkbk...',
        '...kBkbkkBkbk...',
        '...kBkbkkBkbk...',
        '...kBkbkkBkbk...',
      ],
    ],
  },
};

// 16x16 items lying on the ground.
export const DROP_ART = {
  coin: {
    palette: { y: '#ffd23f', Y: '#c99a1a', w: '#fff8d0' },
    rows: [
      '................',
      '.....kkkkkk.....',
      '...kkyyyyyykk...',
      '..kyyyYYYYyyyk..',
      '..kywYYYYYYyyk..',
      '.kyywwykkyYYyyk.',
      '.kyyYyykyyyYyyk.',
      '.kyyYyykkyyYyyk.',
      '.kyyYyyykyyYyyk.',
      '.kyyYYykkyYYyyk.',
      '.kYyyYYYYYYyyYk.',
      '..kyyyYYYYyyyk..',
      '..kYYyyyyyyYYk..',
      '...kkYYYYYYkk...',
      '.....kkkkkk.....',
      '................',
    ],
  },
  feather: {
    palette: { g: '#aab2bd', G: '#d4d9e0', w: '#6e7682' },
    rows: [
      '...........k....',
      '..........kgkk..',
      '.........kgGGwk.',
      '........kgGGwgk.',
      '.......kgGGwwk..',
      '......kgGGwgk...',
      '.....kgGGwwk....',
      '....kgGGwgk.....',
      '...kgGGwwk......',
      '...kGGgwk.......',
      '..kgGwwk........',
      '..kggwk.........',
      '..kwwk..........',
      '..kwk...........',
      '.kkk............',
      '.kk.............',
    ],
  },
  bone: {
    palette: { w: '#f4efe0', W: '#cfc6ad' },
    rows: [
      '................',
      '.........kkk....',
      '........kwwwk...',
      '........kwwwkk..',
      '........kWwwwwk.',
      '........kkwwwwk.',
      '.......kwwwwWWk.',
      '......kkwwWWkk..',
      '..kkkkwwwwkk....',
      '.kwwwkwwWWk.....',
      '.kwwwwwwkk......',
      '.kWWwwwWk.......',
      '..kkwwwk........',
      '...kWWWk........',
      '....kkk.........',
      '................',
    ],
  },
  hyacinth: {
    palette: { g: '#3f8a36', G: '#6fbf4a', v: '#9b6bd6', V: '#d9c2ff' },
    rows: [
      '.......kkk......',
      '......kvvvk.....',
      '.....kkvVvkk....',
      '....kvvvvvvvk...',
      '....kvVvvvvvk...',
      '....kvvvvvvvk...',
      '.....kkvvvkk....',
      '...kkkkkggkk....',
      '..kGGGGkggGGk...',
      '.kGGGGGGgGGGGk..',
      '.kGGGGGGgGGGGk..',
      '.kGGGGGGgGGGGgk.',
      '.kgGGGGggGGGGk..',
      '..kgggggggGGgk..',
      '...kkkkggkggk...',
      '......kggkkk....',
    ],
  },
  scale: {
    palette: { d: '#5a5840', y: '#e3c16f', Y: '#b8923f', L: '#fff0a0' },
    rows: [
      '................',
      '................',
      '...kkkkkkkkkk...',
      '..kLLLLLLLLLLk..',
      '..kyyyyyyyyyyk..',
      '..kyydyydyyyyk..',
      '..kyyyddyyyyyk..',
      '..kyydyydyyyyk..',
      '..kyyyyyyyyyYk..',
      '..kYyyyyyyyYk...',
      '...kYyyydyYk....',
      '....kYyyyYk.....',
      '.....kYyYk......',
      '......kYk.......',
      '.......k........',
      '................',
    ],
  },
  flood_badge: {
    palette: { y: '#ffd23f', Y: '#c99a1a', r: '#d94f4f', b: '#3b82c4', w: '#fff8d0' },
    rows: [
      '...krrrkkbbbk...',
      '...krrrkkbbbk...',
      '....krrkkbbk....',
      '....krrrbbbk....',
      '....krrrbbbk....',
      '.....krrbbk.....',
      '.....kyyyyk.....',
      '....kyyyyyyk....',
      '...kyywYYYyyk...',
      '...kyyYYYYyyk...',
      '..kyyYYYwYYyyk..',
      '...kyyYYYYyyk...',
      '...kyyYYYYyyk...',
      '....kyyyyyyk....',
      '.....kyyyyk.....',
      '......kkkk......',
    ],
  },
  straw: {
    palette: { y: '#e3c16f', Y: '#b8923f', r: '#d94f4f' },
    rows: [
      '...k.k..k..k.k..',
      '..kykykkykkykyk.',
      '..kyYykkykYykyk.',
      '..kyYykkykYykyk.',
      '...kYYykykYykyk.',
      '...kyYykykYykyk.',
      '...kyYykykYykyk.',
      '...kyYykykYykyk.',
      '...krrrrrrrryk..',
      '...krrrrrrrryk..',
      '....kyYykyYkyk..',
      '....kyYykyYkyk..',
      '....kyYYyyYkyk..',
      '.....kyYyyYkyk..',
      '.....kyYyyYkyk..',
      '......kkkkk.k...',
    ],
  },
  stinger: {
    palette: { y: '#ffd23f', b: '#1f1a24', r: '#ff4455' },
    rows: [
      '................',
      '............k...',
      '...........kyk..',
      '..........kbyyk.',
      '.........kybbk..',
      '........kyyybk..',
      '.......kbyykk...',
      '......kybyk.....',
      '.....kyykbk.....',
      '....kyyk.k......',
      '...kyyk.........',
      '..kyyk..........',
      '...kk...........',
      'rk..............',
      '.r..............',
      '................',
    ],
  },
  horn: {
    palette: { h: '#e8e0c8', H: '#b8ad90' },
    rows: [
      '................',
      '...kk...........',
      '..khhk..........',
      '.kHhhhk.........',
      '..kHhhhk........',
      '...khHhk........',
      '...kHhhhk.......',
      '....khhhhk......',
      '....kHhHhhk.....',
      '.....kHhhhhkk...',
      '......kHhhhhhk..',
      '.......kHHHhhHk.',
      '........kkHHhk..',
      '..........kkHk..',
      '............k...',
      '................',
    ],
  },
  speaker: {
    palette: { c: '#2c2733', S: '#8d949e', s: '#3b3f47', g: '#c9ced6', n: '#6dff8a' },
    rows: [
      '................',
      '...nnnnnnnnnn...',
      '..kcccccccccck..',
      '..kccccSScccck..',
      '..kcccSSgSccck..',
      '..kccccSScccck..',
      '..kcccccccccck..',
      '..kcccccccccck..',
      '..kcccSSSSccck..',
      '..kccSSssSScck..',
      '..kccSSssSScck..',
      '..kccSSssSScck..',
      '..kcccSSSSccck..',
      '..kcccccccccck..',
      '..kcccccccccck..',
      '...kkkkkkkkkk...',
    ],
  },
  junk: {
    palette: { a: '#c0c4c8', A: '#8a8f98', r: '#d04a3a', R: '#9c2b24', w: '#ffffff' },
    rows: [
      '................',
      '.......kkkk.....',
      '....kkkRRRRk....',
      '...kaaaaaaaak...',
      '...krrrrrrrk....',
      '..krrrrrrrrrk...',
      '..krrwwwwwwRk...',
      '..kRrrrrrrRk....',
      '...kRrArrrk.....',
      '....krrArrk.....',
      '....krrrrrrk....',
      '...krrrrrrrk....',
      '...kRRRRRRRRk...',
      '...kaaaaaaaaak..',
      '....kkkkkkkkk...',
      '................',
    ],
  },
};

export function shade(hex, f) {
  const n = parseInt(hex.slice(1), 16);
  const c = (v) => Math.max(0, Math.min(255, Math.round(v * f)));
  return `#${[(n >> 16) & 255, (n >> 8) & 255, n & 255].map((v) => c(v).toString(16).padStart(2, '0')).join('')}`;
}

// Blend two colours: t = 0 gives `a`, 1 gives `b`.
export function mix(a, b, t) {
  const A = parseInt(a.slice(1), 16);
  const B = parseInt(b.slice(1), 16);
  const ch = (s) => Math.round(((A >> s) & 255) + (((B >> s) & 255) - ((A >> s) & 255)) * t);
  return `#${[16, 8, 0].map((s) => ch(s).toString(16).padStart(2, '0')).join('')}`;
}

export function characterPalette(look) {
  return {
    k: OUTLINE,
    h: look.hair,
    H: mix(look.hair, '#ffffff', 0.3),
    D: shade(look.hair, 0.7),
    s: look.skin,
    S: shade(look.skin, 0.82),
    w: '#ffffff',
    r: mix(look.skin, '#e8586a', 0.45),
    m: shade(look.skin, 0.6),
    c: look.shirt,
    C: shade(look.shirt, 0.72),
    L: mix(look.shirt, '#ffffff', 0.3),
    p: '#3a3f5c',
    P: '#2a2e45',
    b: '#2a2a2a',
    B: '#4a4a4a',
  };
}

// Draw ASCII rows onto a 2D context.
export function paint(ctx, rows, palette, ox = 0, oy = 0) {
  rows.forEach((row, y) => {
    for (let x = 0; x < row.length; x++) {
      const ch = row[x];
      if (ch === '.') continue;
      const color = ch === 'k' ? palette.k ?? OUTLINE : palette[ch];
      if (!color) continue;
      ctx.fillStyle = color;
      ctx.fillRect(ox + x, oy + y, 1, 1);
    }
  });
}
